# Generated by Django 5.1.7 on 2025-03-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
    ]
