# Generated by Django 5.1.7 on 2025-03-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_equipmentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
