# Generated by Django 5.1.7 on 2025-03-30 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_is_available'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='facilityrequest',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='waitlistbooking',
            name='facility',
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='waitlistbooking',
            name='equipment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlists', to='equipment.equipment'),
        ),
    ]
